# This workflow will build a Java project with Gradle

name: Java CI with Gradle

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build TerraformGenerator
        run:  gradle buildProj:shadowJar
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: buildProj/build/libs
      
      - name: Publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files:      |
                      buildProj/build/libs/*.jar
                      LICENSE
                      
